### ISSUE TITLE
Optimize retrieval and analysis

### ISSUE THREAD

**Issue by pacospace** [thoth-station/report-processing#87]
**Is your feature request related to a problem? Please describe.**
As data to be analyzed are growing, it would be nice for specific daily analysis to retrieve only the document ids that are important for that analysis instead of going through all documents. (e.g analyze adviser document per day, analyze solver documents per solver, or combination of analysis per date, per solver, per source type, etc..)

**Describe the solution you'd like**
Reuse queries from database directly.

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
> /priority awaiting-more-evidence

This should be done for all classes:

- [ ] inspections
- [x] solvers
- [x] adviser
- [ ] security

**Comment by fridex** [comment]
It would make sense to have this implemented only for adviser documents to check system usage. As of now, we do not have any use-case for security or inspections as discussed on the call we had together.

**Comment by goern** [comment]
moin, so is this something we still want do to, or are we happy with the implementation as-is for adviser docs?
